packages:
  - packages/*

catalog:
  '@biomejs/biome': ^2.3.6
  '@changesets/cli': ^2.29.7
  '@types/node': ^24.10.1
  'magic-string': ^0.30.21
  'rimraf': ^6.1.2
  'tsdown': ^0.16.5
  'typescript': ^5.9.3
  'vite': ^7.2.2
  'vitest': ^4.0.10
  'zod': ^4.1.12

publicHoistPattern:
  - '*'
